Controllers/ClientDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBucketApp;
using WebBucketApp.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Text;

namespace WebBucketApp.Controllers
{
    [Authorize(Roles = "Admin,Company")]
    public class ClientDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ClientDetailsController()
        {
        }
        public ClientDetailsController(ApplicationUserManager userManager, ApplicationRoleManager
        roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ??
                HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //public ActionResult Index(string category, string search)
        //{
           
        //    if (!String.IsNullOrEmpty(category))
        //    {
        //        var lk = db.CompanyTokens.Where(a => a.Branch == category);
        //    }
        //    if (!String.IsNullOrEmpty(search))
        //    {
        //        var po = db.ClientDetails.Where(p => p.ClientNo.Contains(search) ||
        //        p.FullName.Contains(search) ||
        //        p.PhoneNumber.Contains(search));
        //        ViewBag.Search = search;
        //    }
        //    var categories = db.CompanyTokens.OrderBy(p => p.Branch).Select(p =>
        //    p.Branch).Distinct();
        //    if (!String.IsNullOrEmpty(category))
        //    {
        //        var kp = db.ClientDetails.Where(a => a.Branch == category);
        //    }
        //    ViewBag.Category = new SelectList(categories);
        //    return View(categories.ToList());
        //}
        public async Task<ActionResult> ClientQuery(string Search)
        {
            //System.Threading.Thread.Sleep(1000);
            var valMgts = db.ClientDetails.Where(s => s.LastName.StartsWith(Search.Trim()) || s.ClientNo.StartsWith(Search.Trim()) || s.FirstName.StartsWith(Search.Trim()) || s.PhoneNumber.StartsWith(Search.Trim()));

            //using (StreamWriter streamWriter = new StreamWriter(@"Z:\Logger\" + $"{DateTime.Now:ddMMyyy}" + ".txt", true))
            //{
            //    streamWriter.WriteLine(DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + " : " + Search + " was queried against the database by " + User.Identity.Name + " and  IP: " + Request.UserHostAddress);
            //}


            return View(await valMgts.ToListAsync());
        }

        // GET: ClientDetails
        public async Task<ActionResult> Index()
        {
            return View(await db.ClientDetails.ToListAsync());
        }
        public ActionResult ClientIndex()
        {
            return View();
        }
        // GET: ClientDetails/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientDetail clientDetail = await db.ClientDetails.FindAsync(id);
            if (clientDetail == null)
            {
                return HttpNotFound();
            }
            return View(clientDetail);
        }

        // Instantiate random number generator.  
        // It is better to keep a single Random instance 
        // and keep using Next on the same instance.  
        private readonly Random _random = new Random();

        // Generates a random number within a range.      
        public int RandomNumber(int min, int max)
        {
            return _random.Next(min, max);
        }
        // Generates a random string with a given size.    
        public string RandomString(int size, bool lowerCase = false)
        {
            var builder = new StringBuilder(size);

            // Unicode/ASCII Letters are divided into two blocks
            // (Letters 65–90 / 97–122):   
            // The first group containing the uppercase letters and
            // the second group containing the lowercase.  

            // char is a single Unicode character  
            char offset = lowerCase ? 'a' : 'A';
            const int lettersOffset = 26; // A...Z or a..z: length = 26  

            for (var i = 0; i < size; i++)
            {
                var @char = (char)_random.Next(offset, offset + lettersOffset);
                builder.Append(@char);
            }

            return lowerCase ? builder.ToString().ToLower() : builder.ToString();
        }
        // Generates a random password.  
        // 4-LowerCase + 4-Digits + 2-UpperCase  
        public string RandomPassword()
        {
            var passwordBuilder = new StringBuilder();

            // 4-Letters lower case   
            passwordBuilder.Append(RandomString(4, true));

            // 4-Digits between 1000 and 9999  
            passwordBuilder.Append(RandomNumber(1000, 9999));

            // 2-Letters upper case  
            passwordBuilder.Append(RandomString(2));
            return passwordBuilder.ToString();
        }

        // GET: ClientDetails/Create
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            
            ClientDetail ng = new ClientDetail()
            {
                TrxnDate = DateTime.Today,
                Branch = user.CompanyToken.Branch,
                Email = user.Email,
                ClientNo= RandomString(10),
            };
            return View(ng);
        }

        // POST: ClientDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,ClientNo,FirstName,LastName,Gender,HomeAddress,CiientEmail,PhoneNumber,IsActive,Email,Branch,TrxnDate")] ClientDetail clientDetail)
        {
            if (ModelState.IsValid)
            {
                db.ClientDetails.Add(clientDetail);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(clientDetail);
        }

        // GET: ClientDetails/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientDetail clientDetail = await db.ClientDetails.FindAsync(id);
            if (clientDetail == null)
            {
                return HttpNotFound();
            }
            return View(clientDetail);
        }

        // POST: ClientDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,ClientNo,FirstName,LastName,Gender,HomeAddress,CiientEmail,PhoneNumber,IsActive,Email,Branch,TrxnDate")] ClientDetail clientDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clientDetail).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(clientDetail);
        }

        // GET: ClientDetails/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClientDetail clientDetail = await db.ClientDetails.FindAsync(id);
            if (clientDetail == null)
            {
                return HttpNotFound();
            }
            return View(clientDetail);
        }

        // POST: ClientDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ClientDetail clientDetail = await db.ClientDetails.FindAsync(id);
            db.ClientDetails.Remove(clientDetail);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CompanyTokensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBucketApp;
using WebBucketApp.Models;
using Microsoft.AspNet.Identity.Owin;

namespace WebBucketApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CompanyTokensController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public CompanyTokensController()
        {
        }
        public CompanyTokensController(ApplicationUserManager userManager, ApplicationRoleManager
        roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ??
                HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        // GET: CompanyTokens
        public async Task<ActionResult> Index()
        {
            return View(await db.CompanyTokens.ToListAsync());
        }

        // GET: CompanyTokens/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyToken companyToken = await db.CompanyTokens.FindAsync(id);
            if (companyToken == null)
            {
                return HttpNotFound();
            }
            return View(companyToken);
        }

        // GET: CompanyTokens/Create
        public ActionResult Create()
        {
            CompanyToken jk = new CompanyToken()
            {
                TrxnDate = DateTime.Now,
            };
            return View(jk);
        }

        // POST: CompanyTokens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Branch,CompToken,ExpirationDate,Email,TrxnDate")] CompanyToken companyToken)
        {
            if (ModelState.IsValid)
            {
                db.CompanyTokens.Add(companyToken);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(companyToken);
        }

        // GET: CompanyTokens/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyToken companyToken = await db.CompanyTokens.FindAsync(id);
            if (companyToken == null)
            {
                return HttpNotFound();
            }
            return View(companyToken);
        }

        // POST: CompanyTokens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Branch,CompToken,ExpirationDate,Email,TrxnDate")] CompanyToken companyToken)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companyToken).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(companyToken);
        }

        // GET: CompanyTokens/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyToken companyToken = await db.CompanyTokens.FindAsync(id);
            if (companyToken == null)
            {
                return HttpNotFound();
            }
            return View(companyToken);
        }

        // POST: CompanyTokens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CompanyToken companyToken = await db.CompanyTokens.FindAsync(id);
            db.CompanyTokens.Remove(companyToken);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Lab.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Rainbow</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
</head>
<body>


    <div class="container body-content">
        <div class="container" style="margin-top:30px">

            <img src="~/Content/WhatsApp Image 2021-02-10 at 10.51.58 AM.jpeg" class="img-fluid mx-auto d-block" width="150" />
            <h5 class="text-center">HARLEY AND RAINBOW SPECIALIZED LABORATORIES</h5>



            <ul class="nav justify-content-center" style="background-color:lightgray;">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("SheetUpload", "Home")">Upload</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("SheetSearchById", "Home")">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("LabReports", "Home")">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "UploadAuditTrails")">Audit Uploads</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "FetchARecordAuditTrails")">Inquiry</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Report</a>
                </li>
            </ul>


        </div>
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - HARLEY AND RAINBOW</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LabReport.cshtml
@{
    ViewBag.Title = "Report";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="container">
        <div style="margin:20px">

        </div>
        <div class="row">

            <div class="col-sm-3">

                <img src="~/Content/lagos-state-logo.jpg" width="150" />
            </div>
            <div class="col-sm-6" style="text-align:center">
                <h4 style="color:green;">HARLEY & RAINBOW SPECIALIZED LABORATORIES</h4>
                <p style="color:red;">A MEMBER OF THE LAGOS COVID-19 LABORATORY CONSORTIUM LAGOS STATE</p>
                <p style="color:green;">
                    LABORATORY INVESTIGATION RESULT PAGE
                </p>
            </div>
            <div class="col-sm-3">
                <img src="~/Content/WhatsApp Image 2021-02-10 at 10.51.58 AM.jpeg" width="200" />
            </div>
        </div>
        <p style="text-decoration:underline;text-align:center">VIROLOGICAL SCREENING TEST FOR COVID-19 OUTBREAK</p>
        <p>Date: </p>
        <div class="row">
            <div class="col">
                <p>
                    NAME:
                </p>
                <p>
                    AGE:
                </p>
                <p>
                    ADDRESS:
                </p>
                <p>
                    PHONE NO:
                </p>
                <p>
                    EMAIL
                </p>
                <p>
                    NATIONALITY
                </p>
            </div>
            <div class="col">
                <p>
                    DATE OF SAMPLE COLLECTED<br />
                </p>
            </div>
            <div class="col">
                <p>
                    SAMPLES(S):<br />
                    SCREENING/REPEAT/FOLLOW
                </p>
                <table class="table table-condensed">
                    <thead>

                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>NASOPHARYNGEAL</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>OROPHARYGEAL</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>SPUTUM</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>BLOOD</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>OTHERS</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>DATE OF RESULT:</td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>POSITIVE</td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>NEGATIVE</td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <p>RESULT: </p>
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>S/N</th>
                    <th>LAB CODE (SPECIMEN USED)</th>
                    <th>REFERENCE RANGE</th>
                    <th>TEST VALUE</th>
                    <th>COMMENT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

            </tbody>
        </table>
        <div>
            <p>
                General Comment:
            </p>
        </div>
        <div>
            <p>
                Name:
            </p>
            <p>
                Designation:
            </p>
            <p>
                Signature
            </p>
        </div>

        <div style="border-radius:10px;background-color:green">
            <p style="color:white;text-align:center">
                72, Adeniyi Jones Avenue, Opposite Lagoon Hospital, Ikeja, Lagos/Customer care lines: 07082091185, 07082014235<br />customercare@harleyandrainbowspecializedlaboratory.com / instagram@harleyrainbow<br />
                website: www.harleyandrainbowspecializedlaboratory.com
            </p>
        </div>
    </div>

</body>
</html>

Views/Shared/_PartialConsole.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - BUCKETT LAUNDRY</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Buckett, Laundry" />
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link href="~/immerse/web/css/bootstrap.min.css" rel="stylesheet" media="all" />
    <link href="~/immerse/web/css/font-awesome.min.css" rel="stylesheet" media="all" />

    <link href="~/immerse/web/css/owl.carousel.css" rel="stylesheet" />

    <link href="~/immerse/web/css/lightbox.css" rel="stylesheet" />

    <link href="~/immerse/web/css/cm-overlay.css" rel="stylesheet" />
    <link href="~/immerse/web/css/formsStyle.css" rel="stylesheet" media="all" />

    @*<link href="~/immerse/web/css/style.css" rel="stylesheet" media="all" />*@

    <!-- Latest compiled and minified CSS -->
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">*@

    <!-- jQuery library -->
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>*@

    <!-- Latest compiled JavaScript -->
    @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@


    <link href="~/immerse/web/fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="~/immerse/web/fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link href="~/immerse/web/fonts.googleapis.com/css?family=Sintony:400,700&amp;subset=latin-ext" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- banner -->
    <div>

        <div class="w3_bandwn">
            <div class="container">
                <div class="col-md-3 w3_l">
                    <i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@rytesoftcompany.net">info@rytesoftcompany.net</a>
                </div>
                <div class="col-md-6 w3_c">
                    <i class="fa fa-phone" aria-hidden="true"></i> +2348062667809
                </div>
                <div class="col-md-3 w3_r">
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h3><a class="navbar-brand" href="@Url.Action("LandingPage", "Home")">BUCKETT</a></h3>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        @*<li><a href="#index.html" class="page-scroll">HOME</a></li>*@


                        <li><a href="@Url.Action("ClientIndex", "ClientDetails")">CLIENT</a></li>

                        <li><a href="@Url.Action("Index", "LaundryManagers")">LAUNDRY</a></li>
                        <li><a href="@Url.Action("Index", "LaundryPayments")">PAYMENT</a></li>
                        <li><a href="@Url.Action("Index", "WashWorkFlows")">ACTIVITY</a></li>
                        @if (Request.IsAuthenticated && User.IsInRole("Company"))
                        {
                            <li><a href="@Url.Action("Dashboard", "Home")">DASHBOARD</a></li>

                        }
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li><a href="@Url.Action("Index", "CompanyTokens")">TOKEN</a></li>
                        }
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {

                            <li><a href="@Url.Action("Index", "Admin")">ADMIN</a></li>
                        }
                        @*<form class="navbar-form navbar-left">
            <div class="w3l_frm">
                <form action="#" method="post">
                    <button type="submit"><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></button>
                    <input type="text" name="search" placeholder="Search" required="">
                </form>
            </div>
        </form>*@
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>

    <!-- footer -->
    <div class="footer" id="footer">
        <div class="container">
            <div class="list">
                <div class="col-md-3 wthree_fl">
                    <a href="#">BUCKETT</a>
                </div>

                <div class="col-md-6 wthree_fc">
                    <h6> RYTESOFT COMPANY </h6>
                    <h6> KETU, LAGOS </h6>
                    <h6> NIGERIA </h6>
                </div>

                <div class="col-md-3 wthree_fr">
                    <h6>+2348062667809</h6>
                    <h6><a href="mailto:info@rytesoftcompany.net">info@rytesoftcompany.net</a></h6>
                </div>


            </div>
        </div>
    </div>
    <!-- //footer -->
    <div class="copyright">
        <div class="container">
            <p>© @DateTime.Now.Year BUCKETT. All rights reserved | Powered by <a href="http://rytesoftcompany.net">RYTESOFT COMPANY</a></p>
        </div>
    </div>

    <script src="~/immerse/web/js/jquery.min.js"></script>
    <script src="~/immerse/web/js/jquery.easing.min.js"></script>
    <script src="~/immerse/web/js/move-top.js"></script>
    <script src="~/immerse/web/js/bootstrap.min.js"></script>
    <script src="~/immerse/web/js/grayscale.js"></script>
    <script src="~/immerse/web/js/SmoothScroll.min.js"></script>
    <!-- flexSlider -->
    <script src="~/immerse/web/js/owl.carousel.js"></script>
    <script>
        $(document).ready(function () {
            $("#owl-demo").owlCarousel({
                items: 2,
                itemsDesktop: [800, 2],
                itemsDesktopSmall: [414, 1],
                lazyLoad: true,
                autoPlay: true,
                navigation: true,

                navigationText: false,
                pagination: true,

            });

        });
    </script>

    <!-- //flexSlider -->
    <!-- /gallery -->
    <script src="~/immerse/web/js/jquery.tools.min.js"></script>
    <script src="~/immerse/web/js/jquery.mobile.custom.min.js"></script>
    <script src="~/immerse/web/js/jquery.cm-overlay.js"></script>

    <script>
        $(document).ready(function () {
            $('.cm-overlay').cmOverlay();
        });
    </script>
    <!-- //gallery -->
    <!-- Move-to-top-->
    <script type="text/javascript">
        $(document).ready(function () {
            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };
            $().UItoTop({ easingType: 'easeOutQuart' });
        });
    </script>
    <!--/Move-to-top-->

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>