Models/ClientDetail.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebBucketApp.Models
{
    public class ClientDetail
    {
        public ClientDetail()
        {
            TrxnDate = DateTime.Now;
            IsActive = true;
        }
        public int ID { get; set; }

        //auto generated
        [Display(Name = "Client ID")]
        public string ClientNo { get; set; }

       
        [Display(Name = "First name"), StringLength(50, MinimumLength = 0)]
        public string FirstName { get; set; }

        [Display(Name = "Surname"), StringLength(50, MinimumLength = 0)]
        public string LastName { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        [Display(Name = "Gender")]
        [DisplayFormat(NullDisplayText = "select gender")]
        public Gender? Gender { get; set; }

        [Display(Name = "Address")]
        [DataType(DataType.MultilineText), MaxLength(250)]
        public string HomeAddress { get; set; }

        [Display(Name = "Client Email")]
        [DataType(DataType.EmailAddress)]
        public string CiientEmail { get; set; }

        [Display(Name = "Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        [Display(Name = "Status")]
        public bool IsActive { get; set; }

        [Display(Name = "Created by")]
        public string Email { get; set; }

        [Display(Name = "Office Branch")]
        public string Branch { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Created Date")]
        public DateTime TrxnDate { get; set; }
    }
    public enum Gender
    {
        Male,Female
    }
}

Controllers/LaundryManagersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBucketApp;
using WebBucketApp.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Web.Helpers;
using Microsoft.AspNet.Identity;
using System.Text;

namespace WebBucketApp.Controllers
{
    [Authorize(Roles = "Admin,Company")]
    public class LaundryManagersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public LaundryManagersController()
        {
        }
        public LaundryManagersController(ApplicationUserManager userManager, ApplicationRoleManager
        roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ??
                HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        // GET: LaundryManagers
        public async Task<ActionResult> Index()
        {
            return View(await db.LaundryManagers.ToListAsync());
        }

        // GET: LaundryManagers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LaundryManager laundryManager = await db.LaundryManagers.FindAsync(id);
            if (laundryManager == null)
            {
                return HttpNotFound();
            }
            return View(laundryManager);
        }
        private bool ValidateFile(HttpPostedFileBase file)
        {
            string fileExtension = System.IO.Path.GetExtension(file.FileName).ToLower();
            string[] allowedFileTypes = { ".gif", ".png", ".jpeg", ".jpg" };
            if ((file.ContentLength > 0 && file.ContentLength < 2097152) &&
            allowedFileTypes.Contains(fileExtension))
            {
                return true;
            }
            return false;
        }
        private void SaveFileToDisk(HttpPostedFileBase file)
        {
            WebImage img = new WebImage(file.InputStream);
            if (img.Width > 190)
            {
                img.Resize(190, img.Height);
            }
            img.Save(Constantsx.ProductImagePath + file.FileName);
            if (img.Width > 100)
            {
                img.Resize(100, img.Height);
            }
            img.Save(Constantsx.ProductThumbnailPath + file.FileName);
        }

        // Instantiate random number generator.  
        // It is better to keep a single Random instance 
        // and keep using Next on the same instance.  
        private readonly Random _random = new Random();

        // Generates a random number within a range.      
        public int RandomNumber(int min, int max)
        {
            return _random.Next(min, max);
        }
        // Generates a random string with a given size.    
        public string RandomString(int size, bool lowerCase = false)
        {
            var builder = new StringBuilder(size);

            // Unicode/ASCII Letters are divided into two blocks
            // (Letters 65–90 / 97–122):   
            // The first group containing the uppercase letters and
            // the second group containing the lowercase.  

            // char is a single Unicode character  
            char offset = lowerCase ? 'a' : 'A';
            const int lettersOffset = 26; // A...Z or a..z: length = 26  

            for (var i = 0; i < size; i++)
            {
                var @char = (char)_random.Next(offset, offset + lettersOffset);
                builder.Append(@char);
            }

            return lowerCase ? builder.ToString().ToLower() : builder.ToString();
        }
        // Generates a random password.  
        // 4-LowerCase + 4-Digits + 2-UpperCase  
        public string RandomPassword()
        {
            var passwordBuilder = new StringBuilder();

            // 4-Letters lower case   
            passwordBuilder.Append(RandomString(4, true));

            // 4-Digits between 1000 and 9999  
            passwordBuilder.Append(RandomNumber(1000, 9999));

            // 2-Letters upper case  
            passwordBuilder.Append(RandomString(2));
            return passwordBuilder.ToString();
        }
        public async Task<ActionResult> ClientQuery(string Search)
        {
            //System.Threading.Thread.Sleep(1000);
            var valMgts = db.LaundryManagers.Where(s =>  s.ClientNo.StartsWith(Search.Trim()) || s.ContractNo.StartsWith(Search.Trim()));

            //using (StreamWriter streamWriter = new StreamWriter(@"Z:\Logger\" + $"{DateTime.Now:ddMMyyy}" + ".txt", true))
            //{
            //    streamWriter.WriteLine(DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + " : " + Search + " was queried against the database by " + User.Identity.Name + " and  IP: " + Request.UserHostAddress);
            //}


            return View(await valMgts.ToListAsync());
        }
        public ActionResult ClientIndex()
        {
            return View();
        }
        // GET: LaundryManagers/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fg = db.ClientDetails.Find(id);
            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            LaundryManager ng = new LaundryManager()
            {
                ClientNo = fg.ClientNo,
                FullName = fg.FullName,
                Email = user.Email,
                Branch=user.CompanyToken.Branch,
                ContractNo= RandomPassword(),
            };
            if (ng == null)
            {
                return HttpNotFound();
            }
            return View(ng);
        }

        // POST: LaundryManagers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,ClientNo,ContractNo,FullName,ShirtNo,TrouserNo,JeanNo,AgbadaCompleteNo,ClientRemark,IsActive,Email,Branch,TrxnDate")] LaundryManager laundryManager)
        {
            if (ModelState.IsValid)
            {
                db.LaundryManagers.Add(laundryManager);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(laundryManager);
        }

        // GET: LaundryManagers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LaundryManager laundryManager = await db.LaundryManagers.FindAsync(id);
            if (laundryManager == null)
            {
                return HttpNotFound();
            }
            return View(laundryManager);
        }

        // POST: LaundryManagers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,ClientNo,ContractNo,FullName,ShirtNo,TrouserNo,JeanNo,AgbadaCompleteNo,ClientRemark,IsActive,Email,Branch,TrxnDate")] LaundryManager laundryManager)
        {
            if (ModelState.IsValid)
            {
                db.Entry(laundryManager).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(laundryManager);
        }

        // GET: LaundryManagers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LaundryManager laundryManager = await db.LaundryManagers.FindAsync(id);
            if (laundryManager == null)
            {
                return HttpNotFound();
            }
            return View(laundryManager);
        }

        // POST: LaundryManagers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            LaundryManager laundryManager = await db.LaundryManagers.FindAsync(id);
            db.LaundryManagers.Remove(laundryManager);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ClientDetails/ClientIndex.cshtml
@{
    ViewBag.Title = "ClientIndex";
    Layout = "~/Views/Shared/_PartialConsole.cshtml";
}

<h2>Client Index</h2>
<div class="form-horizontal jumbotron">

    <h4>Search by Client ID / Name / Phone Number:  </h4>
    <hr />

    <div class="input-group" style="align-content:center">
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
        </span>
        @Html.TextBox("Search", "", new { @class = "form-control", @required = "required", placeholder = "Client ID, Phone No., Full Name" })
        <button type="submit" class="btn btn-danger" id="search"><i class="glyphicon glyphicon-search"></i></button>
    </div>

   

</div>
<div id="results">

</div>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script>


    $(function () {
        $('#search').click(function () {
            var valueSearch = $('#Search').val();
            Search(valueSearch);
        });
    });
    function Search(valueSearch) {
        $.ajax({
            type: "POST",
            url: "/ClientDetails/ClientQuery?Search" + valueSearch,
            async: false,
            data: { Search: valueSearch },
            success: function (data) {
                alert("You are about to Search");
                $("#results").html(data);
            }
        });
    }
</script>

Views/ClientDetails/ClientQuery.cshtml
@model IEnumerable<WebBucketApp.Models.ClientDetail>
@{ 
    Layout = null;
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-responsive table-hover table-striped table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClientNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CiientEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Branch)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrxnDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ClientNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomeAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CiientEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Branch)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrxnDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Views/ClientDetails/Create.cshtml
@model WebBucketApp.Models.ClientDetail

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_PartialConsole.cshtml";
}


<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClientNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientNo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.ClientNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiientEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CiientEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CiientEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Branch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Branch, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Branch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrxnDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrxnDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrxnDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ClientDetails/Delete.cshtml
@model WebBucketApp.Models.ClientDetail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_PartialConsole.cshtml";
}


<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiientEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiientEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrxnDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrxnDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ClientDetails/Details.cshtml
@model WebBucketApp.Models.ClientDetail

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutConsole.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiientEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiientEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrxnDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrxnDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/ClientDetails/Index.cshtml
@model IEnumerable<WebBucketApp.Models.ClientDetail>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PartialConsole.cshtml";
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table table-hover table-responsive table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClientNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CiientEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Branch)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrxnDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClientNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HomeAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CiientEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Branch)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrxnDate)
            </td>
            <td>
                @Html.ActionLink("Laundry", "Create", "LaundryManagers", new { id = item.ID }, null) |
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>